server {
    listen 443 ssl;
    server_name openclaw.xxx.com;
    client_max_body_size 102400M;  #文件最大上传大小10G
    ssl_certificate "/etc/nginx/ssl/xxx.com.pem";
    ssl_certificate_key "/etc/nginx/ssl/xxx.com.key";

    location / {
        proxy_pass http://localhost:3080;  # 这里指定后端服务的地址
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # WebSocket 支持（聊天需要）
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 86400;

        # Disable buffering for SSE streaming
        proxy_buffering off;
        proxy_request_buffering off;
        proxy_cache off;
    }
}
